---
- name: Deploy Lake services
  import_playbook: lake.yaml

- name: Deploy Analytics services
  import_playbook: analytics.yaml

- name: Deploy Orchestrator services
  import_playbook: orchestrator.yaml

- name: Deploy Extractor services
  import_playbook: extractor.yaml

- name: Deploy Jupyter services
  import_playbook: jupyter.yaml

- name: Deploy Monitor services
  import_playbook: monitor.yaml
